letterboxd:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres-warehouse
      port: 5432
      user: postgres
      password: SebAntSav47054!
      dbname: letterboxd_warehouse
      schema: silver
      threads: 4